/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ObsidianKinopoiskPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian9 = require("obsidian");

// Views/search_modal.ts
var import_obsidian3 = require("obsidian");

// APIProvider/provider.ts
var import_obsidian2 = require("obsidian");

// Utils/utils.ts
var import_obsidian = require("obsidian");
function capitalizeFirstLetter(input) {
  if (input.length === 0) {
    return input;
  }
  return input.charAt(0).toUpperCase() + input.slice(1);
}
function replaceIllegalFileNameCharactersInString(text) {
  return text.replace(/[\\/:]/g, ".");
}
function replaceVariableSyntax(movieShow, text) {
  if (!(text == null ? void 0 : text.trim())) {
    return "";
  }
  const entries = Object.entries(movieShow);
  return entries.reduce((result, [key, val = ""]) => {
    return result.replace(new RegExp(`{{${key}}}`, "ig"), val);
  }, text).replace(/{{\w+}}/gi, "").trim();
}
function makeFileName(movieShow, fileNameFormat) {
  let result;
  if (fileNameFormat) {
    result = replaceVariableSyntax(movieShow, fileNameFormat);
  } else {
    result = `${movieShow.name} (${movieShow.year})`;
  }
  return replaceIllegalFileNameCharactersInString(result) + ".md";
}
async function getTemplateContents(app, templatePath) {
  const { metadataCache, vault } = app;
  const normalizedTemplatePath = (0, import_obsidian.normalizePath)(templatePath != null ? templatePath : "");
  if (templatePath === "/") {
    return Promise.resolve("");
  }
  try {
    const templateFile = metadataCache.getFirstLinkpathDest(
      normalizedTemplatePath,
      ""
    );
    return templateFile ? vault.cachedRead(templateFile) : "";
  } catch (err) {
    console.error(
      `Failed to read the daily note template '${normalizedTemplatePath}'`,
      err
    );
    new import_obsidian.Notice("Failed to read the daily note template");
    return "";
  }
}

// APIProvider/provider.ts
async function apiGet(url, token, params = {}, headers) {
  const apiURL = new URL(url);
  Object.entries(params).forEach(([key, value]) => {
    apiURL.searchParams.append(key, value == null ? void 0 : value.toString());
  });
  if (token === "") {
    throw new Error("You need enter API Token");
  }
  const res = await (0, import_obsidian2.requestUrl)({
    url: apiURL.href,
    method: "GET",
    headers: {
      Accept: "*/*",
      "X-API-KEY": token,
      ...headers
    }
  });
  return res.json;
}
async function getByQuery(query, token) {
  try {
    const params = {
      query
    };
    const searchResults = await apiGet(
      "https://api.kinopoisk.dev/v1.4/movie/search",
      token,
      params
    );
    return searchResults.docs;
  } catch (error) {
    console.warn(error);
    throw error;
  }
}
async function getMovieShowById(id, token) {
  try {
    const searchResul = await apiGet(
      `https://api.kinopoisk.dev/v1.4/movie/${id}`,
      token
    );
    return createMovieShowFrom(searchResul);
  } catch (error) {
    console.warn(error);
    throw error;
  }
}
function createMovieShowFrom(fullInfo) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j, _k, _l, _m, _n, _o, _p, _q, _r, _s, _t, _u, _v, _w, _x, _y;
  const seasonsCount = (_b = (_a = fullInfo.seasonsInfo) == null ? void 0 : _a.length) != null ? _b : 0;
  let seriesInSeasonCount = 0;
  if (seasonsCount > 0) {
    const seasonInfo = (_c = fullInfo.seasonsInfo) != null ? _c : [];
    const totalEpisodesCount = seasonInfo.reduce(
      (total, season) => total + season.episodesCount,
      0
    );
    const averageEpisodesCount = totalEpisodesCount / seasonsCount;
    seriesInSeasonCount = Math.ceil(averageEpisodesCount);
  }
  const item = {
    id: fullInfo.id,
    name: fullInfo.name,
    alternativeName: fullInfo.alternativeName,
    year: fullInfo.year,
    description: (_d = fullInfo.description) != null ? _d : "",
    posterUrl: (_f = (_e = fullInfo.poster) == null ? void 0 : _e.url) != null ? _f : "",
    genres: fullInfo.genres.map((genre) => capitalizeFirstLetter(genre.name)).join(", "),
    genresLinks: fullInfo.genres.map((genre) => `"[[${capitalizeFirstLetter(genre.name)}]]"`).join(", "),
    countries: fullInfo.countries.map((country) => country.name).join(", "),
    countriesLinks: fullInfo.countries.map((country) => `"[[${country.name}]]"`).join(", "),
    director: (_h = (_g = fullInfo.persons.find(
      (person) => person.enProfession === "director"
    )) == null ? void 0 : _g.name) != null ? _h : "",
    movieLength: (_i = fullInfo.movieLength) != null ? _i : 0,
    coverUrl: (_k = (_j = fullInfo.backdrop) == null ? void 0 : _j.url) != null ? _k : "",
    logoUrl: (_m = (_l = fullInfo.logo) == null ? void 0 : _l.url) != null ? _m : "",
    isSeries: fullInfo.isSeries,
    seriesLength: (_n = fullInfo.seriesLength) != null ? _n : 0,
    isComplete: ((_o = fullInfo.status) != null ? _o : "") == "completed",
    seasonsCount,
    seriesInSeasonCount,
    kinopoiskUrl: `https://www.kinopoisk.ru/film/${fullInfo.id}/`,
    ratingKp: (_q = (_p = fullInfo.rating) == null ? void 0 : _p.kp) != null ? _q : 0,
    ratingImdb: (_s = (_r = fullInfo.rating) == null ? void 0 : _r.imdb) != null ? _s : 0,
    imdbId: (_u = (_t = fullInfo.externalId) == null ? void 0 : _t.imdb) != null ? _u : "",
    tmdbId: (_w = (_v = fullInfo.externalId) == null ? void 0 : _v.tmdb) != null ? _w : 0,
    kpHDId: (_y = (_x = fullInfo.externalId) == null ? void 0 : _x.kpHD) != null ? _y : ""
  };
  return item;
}

// Views/search_modal.ts
var SearchModal = class extends import_obsidian3.Modal {
  constructor(plugin, callback) {
    super(plugin.app);
    this.callback = callback;
    this.isBusy = false;
    this.query = "";
    this.token = "";
    this.token = plugin.settings.apiToken;
  }
  setBusy(busy) {
    var _a, _b;
    this.isBusy = busy;
    (_a = this.okBtnRef) == null ? void 0 : _a.setDisabled(busy);
    (_b = this.okBtnRef) == null ? void 0 : _b.setButtonText(busy ? "Requesting..." : "Search");
  }
  async search() {
    if (!this.query) {
      throw new Error("No query entered.");
    }
    if (!this.isBusy) {
      try {
        this.setBusy(true);
        const searchResults = await getByQuery(this.query, this.token);
        this.setBusy(false);
        if (!(searchResults == null ? void 0 : searchResults.length)) {
          new import_obsidian3.Notice(`No results found for "${this.query}"`);
          return;
        }
        this.callback(null, searchResults);
      } catch (err) {
        this.callback(err);
      }
      this.close();
    }
  }
  submitEnterCallback(event) {
    if (event.key === "Enter" && !event.isComposing) {
      this.search();
    }
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "\u{1F37F} Search movie or tv show" });
    contentEl.createDiv(
      { cls: "kinopoisk-plugin__search-modal--input" },
      (settingItem) => {
        new import_obsidian3.TextComponent(settingItem).setValue(this.query).setPlaceholder("Search by keyword").onChange((value) => this.query = value).inputEl.addEventListener(
          "keydown",
          this.submitEnterCallback.bind(this)
        );
      }
    );
    new import_obsidian3.Setting(contentEl).addButton((btn) => {
      return this.okBtnRef = btn.setButtonText("Search").setCta().onClick(() => {
        this.search();
      });
    });
  }
  onClose() {
    this.contentEl.empty();
  }
};

// Views/suggest_modal.ts
var import_obsidian4 = require("obsidian");
var ItemsSuggestModal = class extends import_obsidian4.SuggestModal {
  constructor(plugin, suggestion, onChoose) {
    super(plugin.app);
    this.suggestion = suggestion;
    this.onChoose = onChoose;
    this.token = "";
    this.token = plugin.settings.apiToken;
  }
  // Returns all available suggestions.
  getSuggestions(query) {
    return this.suggestion.filter((item) => {
      const searchQuery = query == null ? void 0 : query.toLowerCase();
      return item.name.toLowerCase().includes(searchQuery) || item.alternativeName.toLowerCase().includes(searchQuery);
    });
  }
  // Renders each suggestion item.
  renderSuggestion(item, el) {
    var _a, _b;
    const title = item.name;
    const subtitle = `${item.year}, ${item.alternativeName} (${item.type})`;
    const textInfo = el.createEl("div", {
      attr: { style: "padding-left: 1em;" }
    });
    textInfo.appendChild(el.createEl("div", { text: title }));
    textInfo.appendChild(el.createEl("small", { text: subtitle }));
    const container = el.createEl("div", {
      attr: { style: "display: flex; align-items: center;" }
    });
    container.appendChild(
      el.createEl("img", {
        attr: { src: (_b = (_a = item.poster) == null ? void 0 : _a.url) != null ? _b : "", width: 100 }
      })
    );
    container.appendChild(textInfo);
  }
  // Perform action on the selected suggestion.
  onChooseSuggestion(item) {
    this.getItemDetails(item);
  }
  async getItemDetails(item) {
    try {
      const movieShow = await getMovieShowById(item.id, this.token);
      this.onChoose(null, movieShow);
    } catch (error) {
      this.onChoose(error);
    }
  }
};

// Settings/settings.ts
var import_obsidian7 = require("obsidian");

// Settings/Suggesters/FolderSuggester.ts
var import_obsidian5 = require("obsidian");
var FolderSuggest = class extends import_obsidian5.AbstractInputSuggest {
  constructor(app, textInputEl, onSelectFolder) {
    super(app, textInputEl);
    this.onSelectFolder = onSelectFolder;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const folders = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((folder) => {
      if (folder instanceof import_obsidian5.TFolder && folder.path.toLowerCase().contains(lowerCaseInputStr)) {
        folders.push(folder);
      }
    });
    return folders;
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    this.setValue(file.path);
    this.onSelectFolder(file.path);
    this.close();
  }
};

// Settings/Suggesters/FileSuggester.ts
var import_obsidian6 = require("obsidian");
var FileSuggest = class extends import_obsidian6.AbstractInputSuggest {
  constructor(app, textInputEl, onSelectFile) {
    super(app, textInputEl);
    this.onSelectFile = onSelectFile;
  }
  getSuggestions(inputStr) {
    const abstractFiles = this.app.vault.getAllLoadedFiles();
    const files = [];
    const lowerCaseInputStr = inputStr.toLowerCase();
    abstractFiles.forEach((file) => {
      if (file instanceof import_obsidian6.TFile && file.extension === "md" && file.path.toLowerCase().contains(lowerCaseInputStr)) {
        files.push(file);
      }
    });
    return files;
  }
  renderSuggestion(file, el) {
    el.setText(file.path);
  }
  selectSuggestion(file) {
    this.setValue(file.path);
    this.onSelectFile(file.path);
    this.close();
  }
};

// Settings/settings.ts
var docUrl = "https://github.com/Alintor/obsidian-kinopoisk-plugin";
var apiSite = "https://kinopoisk.dev/";
var DEFAULT_SETTINGS = {
  apiToken: "",
  movieFileNameFormat: "",
  movieFolder: "",
  movieTemplateFile: "",
  seriesFileNameFormat: "",
  seriesFolder: "",
  seriesTemplateFile: ""
};
var ObsidianKinopoiskSettingTab = class extends import_obsidian7.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  get settings() {
    return this.plugin.settings;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.classList.add("obsidian-kinopoisk-plugin__settings");
    const apiKeyDesc = document.createDocumentFragment();
    apiKeyDesc.createDiv({
      text: "You need to get API token to use this plugin. Choose free plan and follow steps."
    });
    apiKeyDesc.createEl("a", {
      text: "Get API Token",
      href: `${apiSite}`
    });
    new import_obsidian7.Setting(containerEl).setName("API Token").setDesc(apiKeyDesc).addText(
      (text) => text.setPlaceholder("Enter your API Token").setValue(this.plugin.settings.apiToken).onChange(async (value) => {
        this.plugin.settings.apiToken = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian7.Setting(containerEl).setName("Movies").setHeading();
    new import_obsidian7.Setting(containerEl).setName("Movie file name").setDesc("Enter the movie file name format.").addText(
      (text) => text.setPlaceholder("Example: {{name}} ({{year}})").setValue(this.plugin.settings.movieFileNameFormat).onChange(async (value) => {
        this.plugin.settings.movieFileNameFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian7.Setting(containerEl).setName("Movie file location").setDesc("New movie notes will be placed here.").addSearch((cb) => {
      try {
        new FolderSuggest(this.app, cb.inputEl, (folder) => {
          this.plugin.settings.movieFolder = folder;
          this.plugin.saveSettings();
        });
      } catch (e) {
      }
      cb.setPlaceholder("Example: folder1/folder2").setValue(this.plugin.settings.movieFolder).onChange((newFolder) => {
        this.plugin.settings.movieFolder = newFolder;
        this.plugin.saveSettings();
      });
    });
    const movieTemplateFileDesc = document.createDocumentFragment();
    movieTemplateFileDesc.createDiv({
      text: "Files will be available as templates."
    });
    movieTemplateFileDesc.createEl("a", {
      text: "Example Template",
      href: `${docUrl}#example-template`
    });
    new import_obsidian7.Setting(containerEl).setName("Movie template file").setDesc(movieTemplateFileDesc).addSearch((cb) => {
      try {
        new FileSuggest(this.app, cb.inputEl, (file) => {
          this.plugin.settings.movieTemplateFile = file;
          this.plugin.saveSettings();
        });
      } catch (e) {
      }
      cb.setPlaceholder("Example: templates/template-file").setValue(this.plugin.settings.movieTemplateFile).onChange((newTemplateFile) => {
        this.plugin.settings.movieTemplateFile = newTemplateFile;
        this.plugin.saveSettings();
      });
    });
    new import_obsidian7.Setting(containerEl).setName("TV series").setHeading();
    new import_obsidian7.Setting(containerEl).setName("TV series file name").setDesc("Enter the tv series file name format.").addText(
      (text) => text.setPlaceholder("Example: {{name}} ({{year}})").setValue(this.plugin.settings.seriesFileNameFormat).onChange(async (value) => {
        this.plugin.settings.seriesFileNameFormat = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian7.Setting(containerEl).setName("TV series file location").setDesc("New tv series notes will be placed here.").addSearch((cb) => {
      try {
        new FolderSuggest(this.app, cb.inputEl, (folder) => {
          this.plugin.settings.seriesFolder = folder;
          this.plugin.saveSettings();
        });
      } catch (e) {
      }
      cb.setPlaceholder("Example: folder1/folder2").setValue(this.plugin.settings.seriesFolder).onChange((newFolder) => {
        this.plugin.settings.seriesFolder = newFolder;
        this.plugin.saveSettings();
      });
    });
    const seriesTemplateFileDesc = document.createDocumentFragment();
    seriesTemplateFileDesc.createDiv({
      text: "Files will be available as templates."
    });
    seriesTemplateFileDesc.createEl("a", {
      text: "Example Template",
      href: `${docUrl}#example-template`
    });
    new import_obsidian7.Setting(containerEl).setName("TV series template file").setDesc(seriesTemplateFileDesc).addSearch((cb) => {
      try {
        new FileSuggest(this.app, cb.inputEl, (file) => {
          this.plugin.settings.seriesTemplateFile = file;
          this.plugin.saveSettings();
        });
      } catch (e) {
      }
      cb.setPlaceholder("Example: templates/template-file").setValue(this.plugin.settings.seriesTemplateFile).onChange((newTemplateFile) => {
        this.plugin.settings.seriesTemplateFile = newTemplateFile;
        this.plugin.saveSettings();
      });
    });
  }
};

// Utils/cursor_jumper.ts
var import_obsidian8 = require("obsidian");
var CursorJumper = class {
  constructor(app) {
    this.app = app;
  }
  async jumpToNextCursorLocation() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian8.MarkdownView);
    if (!activeView) {
      return;
    }
    if (!activeView.file) {
      return;
    }
    const editor = activeView.editor;
    editor.focus();
    editor.setCursor(0, 0);
  }
};

// main.ts
var ObsidianKinopoiskPlugin = class extends import_obsidian9.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("film", "Search in Kinopoisk", () => {
      this.createNewNote();
    });
    this.addCommand({
      id: "open-search-kinopoisk-modal",
      name: "Search",
      callback: () => {
        this.createNewNote();
      }
    });
    this.addSettingTab(new ObsidianKinopoiskSettingTab(this.app, this));
  }
  showNotice(error) {
    try {
      new import_obsidian9.Notice(error.message);
    } catch (e) {
    }
  }
  async createNewNote() {
    try {
      const movieShow = await this.searchMovieShow();
      const {
        movieFileNameFormat,
        movieFolder,
        seriesFileNameFormat,
        seriesFolder
      } = this.settings;
      const renderedContents = await this.getRenderedContents(movieShow);
      const fileNameFormat = movieShow.isSeries ? seriesFileNameFormat : movieFileNameFormat;
      const folderPath = movieShow.isSeries ? seriesFolder : movieFolder;
      const fileName = makeFileName(movieShow, fileNameFormat);
      const filePath = `${folderPath}/${fileName}`;
      const targetFile = await this.app.vault.create(
        filePath,
        renderedContents
      );
      const newLeaf = this.app.workspace.getLeaf(true);
      if (!newLeaf) {
        console.warn("No new leaf");
        return;
      }
      await newLeaf.openFile(targetFile, { state: { mode: "source" } });
      newLeaf.setEphemeralState({ rename: "all" });
      await new CursorJumper(this.app).jumpToNextCursorLocation();
    } catch (err) {
      console.warn(err);
      this.showNotice(err);
    }
  }
  async searchMovieShow() {
    const searchedItems = await this.openSearchModal();
    return await this.openSuggestModal(searchedItems);
  }
  async openSearchModal() {
    return new Promise((resolve, reject) => {
      return new SearchModal(this, (error, results) => {
        return error ? reject(error) : resolve(results != null ? results : []);
      }).open();
    });
  }
  async openSuggestModal(items) {
    return new Promise((resolve, reject) => {
      return new ItemsSuggestModal(this, items, (error, selectedItem) => {
        return error ? reject(error) : resolve(selectedItem);
      }).open();
    });
  }
  async getRenderedContents(movieShow) {
    const { movieTemplateFile, seriesTemplateFile } = this.settings;
    const templateFile = movieShow.isSeries ? seriesTemplateFile : movieTemplateFile;
    if (templateFile) {
      const templateContents = await getTemplateContents(
        this.app,
        templateFile
      );
      const replacedVariable = replaceVariableSyntax(
        movieShow,
        templateContents
      );
      return replacedVariable;
    }
    return "";
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};

/* nosourcemap */